/**
* Generated by MongoDB Relational Migrator 
* https://www.mongodb.com/products/relational-migrator 
* Collection: historialRuta
* Language: JavaScript
* Template: Mongoose
* Generated on 18/10/23

*/
import mongoose from "mongoose";

const Schema = mongoose.Schema;
const model = mongoose.model;

export const historialRuta_Mongoose = new Schema({
    "_id": mongoose.ObjectId,
    "historialRutaFecha": Date,
    "historialRutaHora": Date,
    "historialRutaSalida": String,
    "historialRutaLlegada": String,
    "historialRutaKilometros": String,
    "rutaIdruta": Number,
}, { collection: "historialRuta" })

export const historialRuta_MongooseModel = model("historialRuta_Mongoose", historialRuta_Mongoose);