/**
* Generated by MongoDB Relational Migrator 
* https://www.mongodb.com/products/relational-migrator 
* Collection: rutaActiva
* Language: JavaScript
* Template: Mongoose
* Generated on 18/10/23

*/
import mongoose from "mongoose";

const Schema = mongoose.Schema;
const model = mongoose.model;

export const rutaActiva_Mongoose = new Schema({
    "_id": mongoose.ObjectId,
    "fechaActual": String,
    "distanciaAproximada": Number,
    "posicionActual": Object,
}, { collection: "rutaActiva" })

export const rutaActiva_MongooseModel = model("rutaActiva_Mongoose", rutaActiva_Mongoose);