/**
* Generated by MongoDB Relational Migrator 
* https://www.mongodb.com/products/relational-migrator 
* Collection: ruta
* Language: JavaScript
* Template: Mongoose
* Generated on 18/10/23

*/
import mongoose from "mongoose";

const Schema = mongoose.Schema;
const model = mongoose.model;

export const ruta_Mongoose = new Schema({
    "_id": mongoose.ObjectId,
    "fechaRuta": Date,
    "puntoSalida": String,
    "geosalida": Object,
    "puntoLlegada": String,
    "geollegada": Object,
    "tiempoEstimado": Date,
    "estado": String,
    "medioTransporte": String,
    "alertasAvisosIdalertasAvisos": Number,
    "puntosDeReferenciaIdpuntosReferencia": Number,
}, { collection: "ruta" })

export const ruta_MongooseModel = model("ruta_Mongoose", ruta_Mongoose);