-- MySQL Script generated by MySQL Workbench
-- Fri Oct  6 15:45:05 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema aprendizdb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema aprendizdb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `aprendizdb` DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci ;
USE `aprendizdb` ;

-- -----------------------------------------------------
-- Table `aprendizdb`.`aprendizs`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aprendizdb`.`aprendizs` (
  `id_aprendiz` INT NOT NULL AUTO_INCREMENT,
  `nombre_aprendiz` VARCHAR(100) NOT NULL,
  `password_aprendiz` VARCHAR(20) NOT NULL,
  `email_aprendiz` VARCHAR(20) NOT NULL,
  `fecha_creacion` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `fecha_actualizacion` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_aprendiz`),
  UNIQUE INDEX `idaprendiz_UNIQUE` (`id_aprendiz` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `aprendizdb`.`competencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aprendizdb`.`competencia` (
  `id_competencia` INT NOT NULL AUTO_INCREMENT,
  `nombre_competencia` VARCHAR(50) NOT NULL,
  `fecha_creacion` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `fecha_actualizacion` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_competencia`),
  UNIQUE INDEX `id_competencia_UNIQUE` (`id_competencia` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `aprendizdb`.`notas`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aprendizdb`.`notas` (
  `id_notas` INT NOT NULL AUTO_INCREMENT,
  `nota_1` DECIMAL(5,0) NOT NULL,
  `nota_2` DECIMAL(5,0) NOT NULL,
  `nota_3` DECIMAL(5,0) NOT NULL,
  `fecha_creacion` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `fecha_actualizacion` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_notas`),
  UNIQUE INDEX `id_notas_UNIQUE` (`id_notas` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `aprendizdb`.`resultados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aprendizdb`.`resultados` (
  `id_resultados` INT NOT NULL AUTO_INCREMENT,
  `nombre_resultados` VARCHAR(70) NOT NULL,
  `notas_id_notas` INT NOT NULL,
  `fecha_creacion` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `fecha_actualizacion` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_resultados`, `notas_id_notas`),
  UNIQUE INDEX `id_resultados_UNIQUE` (`id_resultados` ASC) VISIBLE,
  INDEX `fk_resultados_notas1_idx` (`notas_id_notas` ASC) VISIBLE,
  CONSTRAINT `fk_resultados_notas1`
    FOREIGN KEY (`notas_id_notas`)
    REFERENCES `aprendizdb`.`notas` (`id_notas`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `aprendizdb`.`competencia_has_resultados`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aprendizdb`.`competencia_has_resultados` (
  `competencia_id_competencia` INT NOT NULL,
  `resultados_id_resultados` INT NOT NULL,
  `fecha_creacion` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `fecha_actualizacion` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`competencia_id_competencia`, `resultados_id_resultados`),
  INDEX `fk_competencia_has_resultados_resultados1_idx` (`resultados_id_resultados` ASC) VISIBLE,
  INDEX `fk_competencia_has_resultados_competencia_idx` (`competencia_id_competencia` ASC) VISIBLE,
  CONSTRAINT `fk_competencia_has_resultados_competencia`
    FOREIGN KEY (`competencia_id_competencia`)
    REFERENCES `aprendizdb`.`competencia` (`id_competencia`),
  CONSTRAINT `fk_competencia_has_resultados_resultados1`
    FOREIGN KEY (`resultados_id_resultados`)
    REFERENCES `aprendizdb`.`resultados` (`id_resultados`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `aprendizdb`.`instructor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aprendizdb`.`instructor` (
  `id_instructor` INT NOT NULL AUTO_INCREMENT,
  `nombre_instructor` VARCHAR(100) NOT NULL,
  `competencia_has_resultados_competencia_id_competencia` INT NOT NULL,
  `competencia_has_resultados_resultados_id_resultados` INT NOT NULL,
  `fecha_creacion` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `fecha_actualizacion` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  PRIMARY KEY (`id_instructor`, `competencia_has_resultados_competencia_id_competencia`, `competencia_has_resultados_resultados_id_resultados`),
  UNIQUE INDEX `id_instructor_UNIQUE` (`id_instructor` ASC) VISIBLE,
  INDEX `fk_instructor_competencia_has_resultados1_idx` (`competencia_has_resultados_competencia_id_competencia` ASC, `competencia_has_resultados_resultados_id_resultados` ASC) VISIBLE,
  CONSTRAINT `fk_instructor_competencia_has_resultados1`
    FOREIGN KEY (`competencia_has_resultados_competencia_id_competencia` , `competencia_has_resultados_resultados_id_resultados`)
    REFERENCES `aprendizdb`.`competencia_has_resultados` (`competencia_id_competencia` , `resultados_id_resultados`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


-- -----------------------------------------------------
-- Table `aprendizdb`.`aprendiz_has_instructor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `aprendizdb`.`aprendiz_has_instructor` (
  `aprendiz_id_aprendiz` INT NOT NULL,
  `instructor_id_instructor` INT NOT NULL,
  `fecha_creacion` TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
  `fecha_actualizacion` TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
  INDEX `fk_aprendiz_has_instructor_instructor1_idx` (`instructor_id_instructor` ASC) VISIBLE,
  INDEX `fk_aprendiz_has_instructor_aprendiz1_idx` (`aprendiz_id_aprendiz` ASC) VISIBLE,
  CONSTRAINT `fk_aprendiz_has_instructor_aprendiz1`
    FOREIGN KEY (`aprendiz_id_aprendiz`)
    REFERENCES `aprendizdb`.`aprendizs` (`id_aprendiz`),
  CONSTRAINT `fk_aprendiz_has_instructor_instructor1`
    FOREIGN KEY (`instructor_id_instructor`)
    REFERENCES `aprendizdb`.`instructor` (`id_instructor`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4
COLLATE = utf8mb4_0900_ai_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
